from __future__ import annotations

import argparse
import secrets
from pathlib import Path
from urllib.parse import urlparse


ENV_KEYS = {
    "APP_ENV",
    "WEBUI_HOST",
    "WEBUI_PORT",
    "WEBUI_SESSION_SECRET",
    "WEBUI_DOWNLOAD_SECRET",
    "WEBUI_ADMIN_USERNAME",
    "WEBUI_ADMIN_PASSWORD",
    "REMOTE_PUBLIC_BASE_URL",
    "REMOTE_PUBLIC_HOST",
    "WORKER_TUNNEL_MODE",
    "WORKER_SHARED_TOKEN",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare local-only Contabo deployment files without printing secrets.")
    parser.add_argument("--repo-root", default=str(Path(__file__).resolve().parents[1]))
    parser.add_argument("--public-base-url", required=True, help="Public HTTPS base URL, for example https://localizer.example.com")
    parser.add_argument("--admin-username", default="admin")
    parser.add_argument("--admin-password", help="Optional explicit admin password. If omitted, a strong random value is written to .env.")
    parser.add_argument("--port", default="7861")
    parser.add_argument("--force", action="store_true", help="Overwrite existing .env and deploy/config.remote.yaml.")
    parser.add_argument("--allow-http", action="store_true", help="Allow http:// only for private staging tests.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    validate_public_base_url(args.public_base_url, allow_http=args.allow_http)
    written = bootstrap_contabo(
        repo_root,
        public_base_url=args.public_base_url,
        admin_username=args.admin_username,
        admin_password=args.admin_password,
        port=args.port,
        force=args.force,
    )
    print("Contabo bootstrap files prepared.")
    for label, path in written.items():
        print(f"{label}: {path}")
    print("Secrets were written to .env and were not printed.")
    print("Next: python -m ecse_localizer --config deploy/config.remote.yaml deploy-check")
    return 0


def bootstrap_contabo(
    repo_root: Path,
    *,
    public_base_url: str,
    admin_username: str = "admin",
    admin_password: str | None = None,
    port: str = "7861",
    force: bool = False,
) -> dict[str, str]:
    env_path = repo_root / ".env"
    config_path = repo_root / "deploy" / "config.remote.yaml"
    config_example = repo_root / "deploy" / "config.remote.example.yaml"
    if not config_example.exists():
        raise FileNotFoundError(f"Missing template: {config_example}")

    if env_path.exists() and not force:
        raise FileExistsError(f"Refusing to overwrite existing {env_path}. Use --force after backing it up.")
    if config_path.exists() and not force:
        raise FileExistsError(f"Refusing to overwrite existing {config_path}. Use --force after backing it up.")

    values = build_env_values(
        public_base_url=public_base_url,
        admin_username=admin_username,
        admin_password=admin_password,
        port=port,
    )
    env_text = build_env_text(values)
    env_path.write_text(env_text, encoding="utf-8", newline="\n")
    config_text = render_config_template(config_example.read_text(encoding="utf-8"), values)
    config_path.write_text(config_text, encoding="utf-8", newline="\n")
    return {".env": str(env_path), "remote_config": str(config_path)}


def build_env_values(
    *,
    public_base_url: str,
    admin_username: str = "admin",
    admin_password: str | None = None,
    port: str = "7861",
) -> dict[str, str]:
    public_base_url = public_base_url.rstrip("/")
    public_host = public_host_from_url(public_base_url)
    return {
        "APP_ENV": "remote",
        "WEBUI_HOST": "0.0.0.0",
        "WEBUI_PORT": str(port),
        "WEBUI_SESSION_SECRET": random_secret(),
        "WEBUI_DOWNLOAD_SECRET": random_secret(),
        "WEBUI_ADMIN_USERNAME": admin_username,
        "WEBUI_ADMIN_PASSWORD": admin_password or random_secret(24),
        "REMOTE_PUBLIC_BASE_URL": public_base_url,
        "REMOTE_PUBLIC_HOST": public_host,
        "WORKER_TUNNEL_MODE": "reverse-tunnel",
        "WORKER_SHARED_TOKEN": random_secret(),
    }


def build_env_text(values: dict[str, str]) -> str:
    lines = [
        "# Generated by deploy/bootstrap_contabo.py.",
        "# Do not commit this file. It contains deployment secrets.",
    ]
    for key in [
        "APP_ENV",
        "WEBUI_HOST",
        "WEBUI_PORT",
        "WEBUI_SESSION_SECRET",
        "WEBUI_DOWNLOAD_SECRET",
        "WEBUI_ADMIN_USERNAME",
        "WEBUI_ADMIN_PASSWORD",
        "REMOTE_PUBLIC_BASE_URL",
        "REMOTE_PUBLIC_HOST",
        "WORKER_TUNNEL_MODE",
        "WORKER_SHARED_TOKEN",
    ]:
        lines.append(f"{key}={quote_env_value(values[key])}")
    return "\n".join(lines) + "\n"


def render_config_template(text: str, values: dict[str, str]) -> str:
    rendered = text
    for key, value in values.items():
        placeholder = "${" + key + "}"
        rendered = rendered.replace('"' + placeholder + '"', yaml_quote(value))
        rendered = rendered.replace("'" + placeholder + "'", yaml_quote(value))
        rendered = rendered.replace(placeholder, yaml_quote(value))
    return rendered


def yaml_quote(value: str) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def random_secret(nbytes: int = 48) -> str:
    return secrets.token_urlsafe(nbytes)


def quote_env_value(value: str) -> str:
    text = str(value)
    if not text or any(ch.isspace() or ch in {'"', "'", "#", "$", "`"} for ch in text):
        return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return text


def parse_env(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key not in ENV_KEYS:
            continue
        values[key] = unquote_env_value(value.strip())
    return values


def unquote_env_value(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] == '"':
        return value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return value


def validate_public_base_url(value: str, *, allow_http: bool = False) -> None:
    parsed = urlparse(value)
    allowed = {"https"} | ({"http"} if allow_http else set())
    if parsed.scheme not in allowed or not parsed.netloc:
        expected = "https://your-domain.example" if not allow_http else "https://your-domain.example or http://private-host"
        raise ValueError(f"--public-base-url must look like {expected}")


def public_host_from_url(value: str) -> str:
    parsed = urlparse(value)
    if not parsed.netloc:
        raise ValueError("--public-base-url must include a host")
    return parsed.netloc


if __name__ == "__main__":
    raise SystemExit(main())
